### ISSUE TITLE
v0.1.0 feedback from slack

### ISSUE THREAD

**Issue by cppforlife** [k14s/terraform-provider-k14s#1]
k14s provider:

```
provider "k14s" {
  host = "https://1.2.3.4"
  client_certificate     = "${file("~/.kube/client-cert.pem")}"
  client_key             = "${file("~/.kube/client-key.pem")}"
  cluster_ca_certificate = "${file("~/.kube/cluster-ca-cert.pem")}"
  load_config_file = false
}
```

Provider should have same configuration options like official provider https://www.terraform.io/docs/providers/kubernetes/index.html#argument-reference ( Its crucial, I dont want to mess with production clusters )

ytt datasource:

```
terraform {}

provider "k14s" {}

locals {
  value1 = "foobar"
  value2 = "s3cr3t"
  filepath = "./manifest.yaml.a"
}

data "k14s_ytt" "template" {
  files = [local.filepath]
  debug_logs = true
  values_yaml = <<EOF
  #@data/values
  ---
  cm1: local.value1
  cm2: local.value2
EOF
}

output "o" {
  value = data.k14s_ytt.template.result
}
```

1. k14s_ytt datasource works only if filepath is ending with .yaml ( Usually I am using suffixes for manifest where is templating needed ... like manifest.yaml.tpl )

2. Would be nice to expand terraform vars in values_yaml in k14s_ytt datasource.

kapp resource:

1. Required namespace, it should be handled with manifest itself, even kapp do not need namespace

2. Find a way how to show diffs with obfuscated secrets for examplekustomize datasource:
Should be possible to use https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd for CRDs/secrets templating

**Comment by cppforlife** [comment]
related thread: https://kubernetes.slack.com/archives/CH8KCCKA5/p1579041115008800

**Comment by lukasmrtvy** [comment]
datasources shoud have input for inline content and if is needed to include file, there is always an option to use file("/foo/bar") tf interpolation.

**Comment by cppforlife** [comment]
> Provider should have same configuration options like official provider

added common kubeconfig configuration at provider level. also allows to pass in kubeconfig YAML directly. (https://github.com/k14s/terraform-provider-k14s/blob/master/docs/provider.md#input-attributes)

> k14s_ytt datasource works only if filepath is ending with .yaml ( Usually I am using suffixes for manifest where is templating needed ... like manifest.yaml.tpl )

that's a ytt behaviour so wont change that. added values_yaml and values to simpler data value KVs pass through to ytt.

> Required namespace, it should be handled with manifest itself, even kapp do not need namespace

kapp uses namespace configuration for picking where to leave "app record". see kapp's [state namespace](https://github.com/k14s/kapp/blob/master/docs/state-namespace.md) doc.

> datasources shoud have input for inline content and if is needed to include file

ytt and kbld data sources have config_yaml property.

> resource kapp should support --wait flag

kapp has raw_options for deploy and delete (https://github.com/k14s/terraform-provider-k14s/blob/master/docs/k14s_kapp.md#input-attributes)

> resource kapp should support --filter-* flag

kapp has raw_options for delete (https://github.com/k14s/terraform-provider-k14s/blob/master/docs/k14s_kapp.md#input-attributes) so should be able to use --filter-* flags. better yet use kapp's [kapp.k14s.io/delete-strategy annotation](https://github.com/k14s/kapp/blob/master/docs/apply.md#controlling-apply-via-resource-annotations).

**Comment by cppforlife** [comment]
closing this one as v0.4.0 covers all of these features.
