### ISSUE TITLE
Provider swallows kapp errors during the diff phase

### ISSUE THREAD

**Issue by braunsonm** [k14s/terraform-provider-k14s#11]
**What steps did you take:**
If you accidentally provide an incorrect kapp Config, the kapp command will present an error. However this is swallowed with the provider and does not report an error.

**What happened:**
Instead of seeing the error with kapp in the diff section, it just says that there is no change.

**What did you expect:**
The error should be presented and the apply stopped.

**Comment by StevenLocke** [comment]
Thanks for the report, this definitely feels like a bug!  Does this happen with _every_ invalid kapp config? If not, are you able to provide a quick example of an invalid config which causes the terraform-provider to swallow the error?

You noted that you expected the `apply` to stop, in the cases where the invalid config error is swallowed, does kapp make any changes to your cluster?

**Comment by braunsonm** [comment]
Hey @StevenLocke the issue is actually from this: https://github.com/vmware-tanzu/terraform-provider-carvel/issues/14

Initially I had thought it was the kapp error about the diff changing but I think it's actually just this internal terraform error. Closing in favor of #14
