### ISSUE TITLE
Include commands executed in debug logging

### ISSUE THREAD

**Issue by braunsonm** [k14s/terraform-provider-k14s#13]
**Describe the problem/challenge you have**
Sometimes debugging ytt/kapp issues can be difficult. When a templating issue is occurring I would like to iterate quickly, trying different things to solve the problem. Currently I would have to make up a ytt command (which can be very complicated in situations with lots of values), or run tf apply over and over again which is slow and requires a state lock.

**Describe the solution you'd like**
I would like the existing `debug_logs` flag in the ytt data source to output the executed ytt command that it constructs so I have something to easily work off of. 

**Anything else you would like to add:**
This would output secrets to the log potentially so the documentation should be updated to reflect that warning.

**Comment by braunsonm** [comment]
bump

**Comment by braunsonm** [comment]
Still relevant.

**Comment by cppforlife** [comment]
is this still of interest?
