### ISSUE TITLE
Making the provider available in the official terraform registry

### ISSUE THREAD

**Issue by AllaeddineEL** [k14s/terraform-provider-k14s#21]
**Describe the problem/challenge you have**
Right now the provider need to be installed manually on the system running terraform. And whenever there is a new version need to be installed manually as well. 

**Describe the solution you'd like**
The LCM of the provider can enhanced by pushing the provider's binaries to [the official terraform registry](https://registry.terraform.io/), and terraform will automatically pull the provider from the registry

**Comment by lukasmrtvy** [comment]
duplicate https://github.com/vmware-tanzu/terraform-provider-carvel/issues/6

**Comment by cppforlife** [comment]
closing per above comment.
