### ISSUE TITLE
Please create arm64 provider

### ISSUE THREAD

**Issue by marcinkubica** [k14s/terraform-provider-k14s#30]
**Describe the problem/challenge you have**
Can't use a provider on apple M1

**Describe the solution you'd like**
Use provider on apple M1 via terraform.registry.io

Cheers
Marcin

**Comment by asalan316** [comment]
I am looking for vmware-tanzu/caravel for the M1.

**Comment by marcinkubica** [comment]
hi @cppforlife
do you think you have a chance to look at this for us? thanks.

**Comment by pivotaljohn** [comment]
No question: we want this.

Carvel maintainers are eyeing #29 for the near future. This need could be addressed concurrently.

That said, will definitely accept contributions around this, too.

**Comment by marcinkubica** [comment]
Hi @pivotaljohn 
With @asalan316 we have compiled carvel and tried it locally for arm64 apple M1 and it worked just fine. Not sure though how we can help in releasing it to terraform registry.

**Comment by asalan316** [comment]
As @marcinkubica said, it worked by using local go binary on Apple Silicon. But, probably need some help to release it in order to fix the issue.

**Comment by mou** [comment]
Hi, @pivotaljohn. I am ready to contribute. Our team decided to move to `ytt` from plain `templatefile()`. But we are facing a problem with the support of recent M1 Macs. Since the release to the registry is not codified, there is not much external contributor can do about.

With the artifact generation as i can see, project uses `goreleaser` to generate releases, but github action version was not updated for 2 years, so most likely that version does not support recent architectures. Maybe we should start by simply bumping `goreleaser` version?

**Comment by praveenrewar** [comment]
> Maybe we should start by simply bumping goreleaser version?

Makes sense 💯  @mou Please feel free to make a PR for it :)

**Comment by mou** [comment]
@praveenrewar I created a PR #34  which should solve the exact issue. But it is need verification and as I understand publication to the registry is something that should be performed manually by the team of maintainers.

**Comment by VLukyanov84** [comment]
It will be an excellent investment in the development of the carvel project
@mou thx

**Comment by agrechin** [comment]
The lack of arm64 support is a show-stopper, tbh.

**Comment by gordonswing** [comment]
`arm64` is a must-have option here, please, take it into consideration to speed up the PR

**Comment by joaopapereira** [comment]
Hey, due to a change in Github org, we had to update the provider. Here is the new link https://registry.terraform.io/providers/carvel-dev/carvel/latest

**Comment by mou** [comment]
Thank you very much for so quick review and release. You saved a lot of internal Q&A time for our team.
