### ISSUE TITLE
Update examples to follow more inclusive language.

### ISSUE THREAD

**Issue by aaronshurley** [k14s/terraform-provider-k14s#31]
**Describe the problem/challenge you have**
Update the examples to follow more inclusive language.

**Describe the solution you'd like**
An update of the examples so that the inclusive naming checker job passes without ignoring the following examples:
- examples/guestbook/ytt-config/redis-slave.yaml
- examples/guestbook/ytt-config/guestbook-all-in-one.yaml

**Anything else you would like to add:**
See [this issue](https://github.com/vmware-tanzu/carvel/issues/594) for more context.

Upon making these changes, ensure that [this blog post is still accurate](https://carvel.dev/blog/terraform-carvel-provider/).

**Comment by joaopapereira** [comment]
The associated PRs were merge, going to close the issue
