### ISSUE TITLE
Kapp diff during plan phase

### ISSUE THREAD

**Issue by braunsonm** [k14s/terraform-provider-k14s#5]
Hi there!

I just had a question about this resource I didn't see in the docs.

Can the kapp resource output the diff even during the `terraform plan` phase? I see the option to enable diff output but I would have assumed that only outputs when you `apply`

**Comment by cppforlife** [comment]
im pretty sure `terraform plan` shows you kapp diff. what output do you see?

**Comment by braunsonm** [comment]
Thanks @cppforlife this was just a question is all.

**Comment by braunsonm** [comment]
Re-opening this as this is not the case. It would be really great to have this working properly. Otherwise we'll be calling `apply` and cancelling it on the pipelines

**Comment by braunsonm** [comment]
As a not very ideal workaround for now in pipelines:

`scripts/terraform-plan.sh`

```bash
#!/usr/bin/expect -f

set timeout -1

spawn ./scripts/terraform-apply.sh

expect "*Enter a value:*"

send -- "n\r"

expect eof
```

`scripts/terraform-apply.sh`

```bash
#!/bin/bash

terraform apply -input=false
```
