### ISSUE TITLE
(feat): Add terraform-provider-carvel provider to https://registry.terraform.io/

### ISSUE THREAD

**Issue by lukasmrtvy** [k14s/terraform-provider-k14s#6]
**Describe the problem/challenge you have**
- auto installation of provider
- usage in Terraform Cloud
- versioned constrains

**Describe the solution you'd like**
Add terraform-provider-carvel provider to https://registry.terraform.io/

**Anything else you would like to add:**
no

Thanks

Related: https://github.com/vmware-tanzu/terraform-provider-carvel/issues/19

**Comment by danielhelfand** [comment]
Thanks for opening this @lukasmrtvy. More information on the process is available [here](https://www.terraform.io/docs/registry/providers/publishing.html?_ga=2.16639537.602837531.1610382416-1171296398.1610382416) for anyone interested in picking this up.

**Comment by braunsonm** [comment]
Hi there, we're really interested in using this provider it would be great to have this in the registry.

**Comment by slushysnowman** [comment]
Is there a progress update for this? I see it was set to in progress on March 16th but nothing since then.

**Comment by bonzofenix** [comment]
+1

**Comment by cppforlife** [comment]
sorry folks it took some time. added https://registry.terraform.io/providers/vmware-tanzu/carvel/latest.
